var Firstname = "somanath sahoo";
var Age = "20";
var Gender = "male";
console.log(Firstname + " " + Age + " " + Gender);
var physics = 50;
var It = 85;
var English = 70;
var Math = 55;
var chemistry = 62;
var sum = physics + It + English + Math + chemistry;
console.log(sum);
var avg = sum / 5;
console.log(avg);
var studentname = "Debashish jena";
var Age = "21";
var Gender = "male";
console.log(studentname + " " + Age + " " + Gender);
var physics = 30;
var It = 75;
var English = 90;
var Math = 85;
var chemistry = 72;
var total = physics + It + English + Math + chemistry;
console.log(total);
var avg = total/5;
console.log(avg);
var Firstname = "Dinesh panda";
var age = "22";
var gender = "male";
console.log(Firstname+" "+age+" "+gender);
var physics = 50;
var chemistry = 52;
var It = 86;
var english = 95;
var math =65;
var sum = physics+chemistry+It+english+math;
console.log(sum);
var total = sum/5;
console.log(total);
var Firstname = "Bhabani Khuntia";
var age = "28";
var Gender = "male";
console.log(Firstname+" "+age+" "+Gender);
var english = 55;
var chemistry = 68;
var math = 77;
var physics = 89;
var it = 98;
var sum = english+chemistry+math+physics+it;
console.log(sum);
var avg= sum/5;
console.log(avg);
var firstname = "Deepti Padhi";
var age = "25";
var gender = "female";
console.log(firstname+" "+age+" "+gender);
var physics = 78;
var chemistry = 95;
var english = 82;
var it = 79;
var math = 85;
var total = 78+95+82+79+85;
console.log(total);
var avg = total/5;
console.log(avg);
alert("Hello World");